apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kbot.fullname" . }}
  labels:
    {{- include "kbot.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kbot.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}-{{ .Values.image.arch }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app/kbot","start"]
          env:
            - name: TELE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-telegram-token
                  key: TELE_TOKEN
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
